### PR TITLE
Add Dockerfile, .dockeringore for .env, and update README with basic …

### LINKED ISSUE #33: Feature: Create dockerfile
It'd be easy to create a dockerfile for the app, that way contributors have a single command to run the app and don't need to install or upgrade nodejs.

### PR DESCRIPTION
**Pull request by ecliptik**
…docker instructions

Fixes #33

Built and tested locally, however page gives a `Something went wrong!` error, probably because `GOOGLE_API_KEY` isn't set.

### CODE REVIEW

**Comment by Alex-Cannon** [comment]
@ecliptik thanks for the contribution! I also built and tested locally with the correct GOOGLE_API_KEY and everything functioned correctly. Would you make 2 small changes to reviews I left?

Thanks!

**Comment by ecliptik** [comment]
@Alex-Cannon I can make changes, although I don't see any review comments on the PR. Are they somewhere else?

**Comment by Alex-Cannon** [comment]
@ecliptik my bad. I didn't submit my review. Should be available now.

**Comment by ecliptik** [comment]
@Alex-Cannon np, changes made and updated the branch.

**Pull request merged**
